### ISSUE TITLE
while testing the fail2ban.php page i noticed the page tries to load for a minute before it gives up.

### ISSUE THREAD

**Issue by Jieiku** [Egregius/centralized_fail2ban#1]
while testing the fail2ban.php page i noticed the page tries to load for a minute before it gives up, the same behavior is seen when you curl the page as well. Maybe its not an issue on all systems, I am running Ubuntu 20.04 with nginx as the web server.

I found the culprit to be this line and commented it out, the ips still make it to the db, so as far as I can tell the line is not strictly necessary:

`//header('Content-Length: ' . strlen($html));`

**Comment by Egregius** [comment]
Thanks for the tip
