### ISSUE TITLE
while testing the blockedips.php I noticed that pressing the unblock button does not take affect until your next ban comes in.

### ISSUE THREAD

**Issue by Jieiku** [Egregius/centralized_fail2ban#2]
while testing the blockedips.php I noticed that pressing the unblock button does not take affect until your next ban comes in.

The reason for this is pressing the unblock button DOES remove the IP from the database, but it does not regenerate the txt file, that function "create_txt()" lives in the fail2ban.php file.

So if you unban somebody using the blockedips.php they wont actually get unbanned until a new ban comes in and the txt file gets rewritten.

additionally blockedips.php requires jquerry as well as datatables and datatables.columnfilter... this was not mentioned in the readme but I did eventually figure it out.

**Comment by Jieiku** [comment]
I actually resolved this on my copy, edit blockedips.php:

`nano blockedips.php`

after this line:
`$stmt->execute();`

add:
`create_txt();`

then at the bottom of the file add this:
```

function create_txt() {
	global $db;
	$html=null;
	$stmt=$db->query("SELECT `1`, `2`, `3`, `4` from fail2ban order by `1`, `2`, `3`, `4`");
	while ($i=$stmt->fetch(PDO::FETCH_ASSOC)) {
		$html.=$i['1'].'.'.$i['2'].'.'.$i['3'].'.'.$i['4'].'/32
';	
	}
	header('Content-Type:text/plain');
	//header('Content-Length: ' . strlen($html));
	header('Content-Transfer-Encoding: binary');
	header('Cache-Control: must-revalidate');
	header('Pragma: public');
	file_put_contents('/temp/badips.txt', $html);
	shell_exec('/usr/bin/aggregate </temp/badips.txt >/var/www/mydomain.be/badips.txt');
        $URI = $_SERVER['REQUEST_URI'];
        header("location:$URI");
}
```

What this does is create_txt() only gets called if the Unblock button is pressed, and after the end of the create_txt() function it will revisit the page (this time without requesting an unblock.)

**Comment by Egregius** [comment]
Thanks for this!
