### ISSUE TITLE
CSS and JS Files

### ISSUE THREAD

**Issue by ObiWanCanOweMe** [Egregius/centralized_fail2ban#3]
Hi,

Any chance you could add the CSS and JS files to the repo?

Thanks!

**Comment by Egregius** [comment]
I added the js files and some basic CSS. Not that simple to test if it's ok as my page has grown with other functions etc.

**Comment by ObiWanCanOweMe** [comment]
Works great, thanks!

**Comment by Egregius** [comment]
You're welcome ;)
